steps:
  # Grab cached M2 repo
  - name: gcr.io/cloud-builders/gsutil
    id: Get M2 Cache
    args: ['cp', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz', 'm2.tar.gz']
      #
  # See https://github.com/GoogleCloudPlatform/cloud-builders-community to get the tar command
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Expand M2 Cache
    args: ['xpzf', 'm2.tar.gz']

  - name: 'maven:3-jdk-11'
    id: Maven Test
    secretEnv: [ 'DEPLOY_KEY' ]
    env:
      - TZ=Europe/London
    args: ['-Dmaven.repo.local=/workspace/.m2/repository', 'test']
    entrypoint: bash
    args:
      - '-c'
      - |
        cp .mvn/cloudbuild-settings.xml /tmp
        sed -ie "s/\[GIT_DEPLOY_TOKEN\]/S$DEPLOY_KEY/" /tmp/cloudbuild-settings.xml
        mvn release:prepare -s /tmp/cloudbuild-settings.xml
        mvn release:perform -s /tmp/cloudbuild-settings.xml


availableSecrets:
  secretManager:
    - versionName: projects/415467542055/secrets/sdc-int-common-deploy-key/versions/1
      env: 'DEPLOY_KEY'


