steps:
  # Grab cached M2 repo
  - name: gcr.io/cloud-builders/gsutil
    id: Get M2 Cache
    args: ['cp', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz', 'm2.tar.gz']
      #
  # See https://github.com/GoogleCloudPlatform/cloud-builders-community to get the tar command
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Expand M2 Cache
    args: ['xpzf', 'm2.tar.gz']

  - name: openjdk:11-jdk-slim
    id: Prepare JDK11
    entrypoint: bash
    args:
      - -c
      - |
        which java
    volumes:
      - name: javahome
        path: /usr/local/openjdk-11

  - name: gcr.io/cloud-builders/git
    id: Maven Release
    secretEnv: [ sdc-int-common-deploy-key ]
    env:
      - TZ=Europe/London
      - JAVA_HOME=/usr/local/openjdk-11
    args: ['-Dmaven.repo.local=/workspace/.m2/repository', 'test']
    entrypoint: bash
    args:
      - '-c'
      - |
        git config --global user.name sdc-ci
        git config --global user.email philip.whiles@ext.ons.gov.uk
        cp .mvn/cloudbuild-settings.xml /tmp
        sed -ie "s/\[GIT_DEPLOY_TOKEN\]/$$sdc-int-common-deploy-key/" /tmp/cloudbuild-settings.xml
        cd /workspace
        ./mvnw -B release:prepare -s /tmp/cloudbuild-settings.xml -Dmaven.repo.local=/workspace/.m2/repository
        ./mvnw -B release:perform -s /tmp/cloudbuild-settings.xml -Dmaven.repo.local=/workspace/.m2/repository
    volumes:
      - name: javahome
        path: /usr/local/openjdk-11

  # Update M2 repo cache
  - name: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-ci/cloudbuild/tar
    id: Compress M2 Cache
    args: ['cpzf', 'm2.tar.gz', '.m2']

  - name: gcr.io/cloud-builders/gsutil
    id: Save M2 Cache
    args: ['cp', 'm2.tar.gz', 'gs://ons-ci-int-cloudbuild-maven-cache/m2.tar.gz']

availableSecrets:
  secretManager:
    - versionName: projects/415467542055/secrets/sdc-int-common-deploy-key/versions/1
      env: sdc-int-common-deploy-key


