
# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: INFO
    org.springframework: INFO
  profile: DEV
  useJson: true

  

