package uk.gov.ons.ctp.common.event;

public enum Source {
  ACTION_EXPORTER,
  ADDRESS_RESOLUTION,
  CASE_SERVICE,
  CONTACT_CENTRE_API,
  FIELDWORK_GATEWAY,
  NOTIFY_GATEWAY,
  RECEIPT_SERVICE,
  RESPONDENT_HOME,
  SAMPLE_LOADER;
}
